services:
  - type: web
    name: bug-tracker
    env: node
    plan: free
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: REACT_APP_API_URL
        value: https://bugtracker-vbr3.onrender.com
