services:
  - type: web
    name: bug-tracker-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000

  - type: web
    name: bug-tracker-frontend
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run serve
    envVars:
      - key: REACT_APP_API_URL
        value: https://bug-tracker-backend.onrender.com 