services:
  - type: web
    name: bug-tracker
    env: node
    plan: free
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
      cd ../server && npm install express mongoose cors dotenv
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: REACT_APP_API_URL
        value: https://bug-tracker.onrender.com 